# Generated by Django 5.1 on 2024-08-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100)),
                ('quant_tentativas', models.IntegerField()),
                ('data_hora_partida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
