# Generated by Django 5.1 on 2024-09-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_partida_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='tempo_duracao',
        ),
    ]
