# Generated by Django 5.1 on 2024-09-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_partida_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='tempo_duracao',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
