# Generated by Django 5.1 on 2024-09-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_partida_tempo_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='tempo_duracao',
            field=models.FloatField(null=True),
        ),
    ]
